In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/processed/car_new_details.csv")

In [3]:
df["Car_Age"] = 2022 - df["Year"]

In [4]:
df["Kilometers_Per_Year"] = (df["Kilometer"] / df["Car_Age"].replace(0, 1)).round(4)

In [5]:
owner_mapping = {
    "Unregistered Car": 0,
    "First": 1,
    "Second": 2,
    "Third": 3,
    "Fourth": 4,
    "4 or More": 4
}

df["Owner_Count"] = df["Owner"].map(owner_mapping)

df["Unregistered"] = (df["Owner"] == "Unregistered Car").astype(int)

In [6]:
df["Fuel Type"] = df["Fuel Type"].replace({
    "CNG + CNG": "CNG",
    "Petrol + CNG": "CNG",
    "Petrol + LPG": "LPG",
})

print(df["Fuel Type"].value_counts())

Fuel Type
Diesel      1047
Petrol       942
CNG           52
Electric       7
LPG            6
Hybrid         3
Name: count, dtype: int64

In [7]:
df[[
    "Year",
    "Car_Age",
    "Kilometer",
    "Kilometers_Per_Year",
    "Owner",
    "Owner_Count",
    "Unregistered"
]].head(10)

,Year,Car_Age,Kilometer,Kilometers_Per_Year,Owner,Owner_Count,Unregistered
0,2017,5,87150,17430.0000,First,1,0
1,2014,8,75000,9375.0000,Second,2,0
2,2011,11,67000,6090.9091,First,1,0
3,2019,3,37500,12500.0000,First,1,0
4,2018,4,69000,17250.0000,First,1,0
5,2017,5,73315,14663.0000,First,1,0
6,2015,7,47000,6714.2857,Second,2,0
7,2017,5,75000,15000.0000,Second,2,0
8,2017,5,56000,11200.0000,First,1,0
9,2015,7,85000,12142.8571,First,1,0

In [8]:
df[[
    "Car_Age",
    "Kilometers_Per_Year",
    "Owner_Count",
    "Unregistered"
]].describe()

           Car_Age  Kilometers_Per_Year  Owner_Count  Unregistered
count  2057.000000          2057.000000  2057.000000   2057.000000
mean      5.575109         10997.023610     1.217793      0.010209
std       3.365007          7247.824147     0.493355      0.100547
min       0.000000             0.000000     0.000000      0.000000
25%       3.000000          6428.571400     1.000000      0.000000
50%       5.000000          9398.400000     1.000000      0.000000
75%       8.000000         13666.666700     1.000000      0.000000
max      34.000000        110000.000000     4.000000      1.000000

In [9]:
print("Missing values:")
print(df[[
    "Car_Age",
    "Kilometers_Per_Year",
    "Owner_Count",
    "Unregistered"
]].isnull().sum())

Missing values:
Car_Age                0
Kilometers_Per_Year    0
Owner_Count            0
Unregistered           0
dtype: int64

In [10]:
print(df["Owner_Count"].value_counts().sort_index())

Owner_Count
0      21
1    1617
2     373
3      42
4       4
Name: count, dtype: int64

In [11]:
top_locations = df["Location"].value_counts().head(10).index

df["Location_Grouped"] = df["Location"].where(
    df["Location"].isin(top_locations),
    "Other"
)

In [12]:
print(df["Location_Grouped"].value_counts())

Location_Grouped
Other        693
Mumbai       342
Delhi        307
Pune         144
Bangalore    132
Hyderabad    116
Lucknow       78
Ahmedabad     70
Chennai       63
Kolkata       60
Kanpur        52
Name: count, dtype: int64

In [13]:
df.to_csv("../data/processed/car_new_details.csv", index=False)

In [14]:
categorical_columns = [
    "Make",
    "Model",
    "Fuel Type",
    "Transmission",
    "Color",
    "Seller Type",
    "Drivetrain",
    "Location_Grouped"
]

for col in categorical_columns:
    print(f"{col}: {df[col].nunique()} unique values")

Make: 33 unique values
Model: 1049 unique values
Fuel Type: 6 unique values
Transmission: 2 unique values
Color: 17 unique values
Seller Type: 3 unique values
Drivetrain: 4 unique values
Location_Grouped: 11 unique values

In [15]:
for col in df.columns:
    print(f"\n--- {col} ({df[col].nunique()} unique) ---")
    print(df[col].value_counts(dropna=False))

--- Make (33 unique) ---
Make
Maruti Suzuki    440
Hyundai          348
Mercedes-Benz    171
Honda            158
Toyota           132
Audi             127
BMW              121
Mahindra         119
Tata              57
Volkswagen        50
Ford              48
Renault           42
Skoda             40
Land Rover        33
Kia               23
Jeep              18
MG                17
Jaguar            17
Nissan            16
Volvo             16
Porsche           15
MINI              11
Datsun             8
Chevrolet          7
Lexus              6
Mitsubishi         4
Ssangyong          3
Rolls-Royce        3
Isuzu              2
Fiat               2
Maserati           1
Ferrari            1
Lamborghini        1
Name: count, dtype: int64

--- Model (1049 unique) ---
Model
X1 sDrive20d xLine                     15
Swift DZire VDI                        14
Fortuner 2.8 4x2 AT [2016-2020]        13
City V                                 13
Swift DZire VXI                        12
                                       ..
Grand i10 Asta 1.1 CRDi [2013-2016]     1
GLS 400 4MATIC                          1
Ritz Vxi (ABS) BS-IV                    1
XUV500 W8 [2015-2017]                   1
Figo Duratec Petrol ZXI 1.2             1
Name: count, Length: 1049, dtype: int64

--- Price (619 unique) ---
Price
425000     26
625000     24
650000     22
375000     20
450000     19
           ..
1639999     1
2765000     1
891000      1
4290000     1
670000      1
Name: count, Length: 619, dtype: int64

--- Year (22 unique) ---
Year
2018    267
2017    262
2019    218
2014    192
2016    186
2015    178
2021    156
2020    132
2013    128
2012     92
2022     81
2011     79
2009     33
2010     27
2008     13
2007      6
2006      2
2004      1
2002      1
1988      1
2000      1
1996      1
Name: count, dtype: int64

--- Kilometer (845 unique) ---
Kilometer
65000    33
72000    32
75000    29
45000    29
50000    29
         ..
21200     1
75        1
75693     1
90300     1
60474     1
Name: count, Length: 845, dtype: int64

--- Fuel Type (6 unique) ---
Fuel Type
Diesel      1047
Petrol       942
CNG           52
Electric       7
LPG            6
Hybrid         3
Name: count, dtype: int64

--- Transmission (2 unique) ---
Transmission
Manual       1131
Automatic     926
Name: count, dtype: int64

--- Location (77 unique) ---
Location
Mumbai              342
Delhi               307
Pune                144
Bangalore           132
Hyderabad           116
                   ...
Valsad                1
Rohtak                1
Faizabad              1
Pimpri-Chinchwad      1
Siliguri              1
Name: count, Length: 77, dtype: int64

--- Color (17 unique) ---
Color
White     800
Silver    285
Grey      220
Blue      190
Black     163
Red       154
Brown      82
Maroon     37
Gold       30
Bronze     28
Green      17
Orange     16
Others     12
Yellow      9
Beige       8
Purple      5
Pink        1
Name: count, dtype: int64

--- Owner (6 unique) ---
Owner
First               1617
Second               373
Third                 42
Unregistered Car      21
Fourth                 3
4 or More              1
Name: count, dtype: int64

--- Seller Type (3 unique) ---
Seller Type
Individual                 1995
Corporate                    57
Commercial Registration       5
Name: count, dtype: int64

--- Engine (108 unique) ---
Engine
1197    231
1498    144
1248    122
998     121
1497     84
       ...
2157      1
936       1
2400      1
793       1
995       1
Name: count, Length: 108, dtype: int64

--- Max Power (166 unique) ---
Max Power
89.0     139
67.0      98
116.0     90
82.0      62
74.0      61
        ...
78.0       1
77.0       1
236.0      1
198.0      1
329.0      1
Name: count, Length: 166, dtype: int64

--- Max Torque (141 unique) ---
Max Torque
200.0    205
400.0    114
115.0     84
114.0     76
90.0      73
        ...
319.0      1
222.0      1
490.0      1
134.0      1
456.0      1
Name: count, Length: 141, dtype: int64

--- Drivetrain (4 unique) ---
Drivetrain
FWD        1328
RWD         321
AWD         272
Unknown     136
Name: count, dtype: int64

--- Length (248 unique) ---
Length
3995.0    221
4370.0     96
4440.0     70
4270.0     57
3985.0     55
         ...
4314.0      1
4320.0      1
4818.0      1
4797.0      1
4249.0      1
Name: count, Length: 248, dtype: int64

--- Width (170 unique) ---
Width
1695.0    201
1770.0     93
1780.0     62
1790.0     61
1680.0     51
         ...
1704.0      1
1755.0      1
1715.0      1
1764.0      1
2032.0      1
Name: count, Length: 170, dtype: int64

--- Height (196 unique) ---
Height
1475.0    87
1505.0    80
1545.0    80
1530.0    63
1520.0    61
          ..
1518.0     1
1523.0     1
1655.0     1
1486.0     1
1503.0     1
Name: count, Length: 196, dtype: int64

--- Seating Capacity (6 unique) ---
Seating Capacity
5.0    1677
7.0     273
4.0      42
8.0      35
6.0      23
2.0       7
Name: count, dtype: int64

--- Fuel Tank Capacity (55 unique) ---
Fuel Tank Capacity
50.0     244
35.0     222
60.0     155
45.0     154
43.0     145
55.0     117
42.0     111
40.0     106
80.0      92
37.0      89
66.0      59
70.0      59
65.0      55
48.0      51
57.0      44
64.0      31
28.0      30
63.0      30
75.0      30
32.0      27
52.0      20
44.0      20
93.0      18
100.0     15
54.0      14
67.0      12
56.0      11
90.0      10
78.0       7
51.0       6
41.0       6
83.0       6
27.0       5
85.0       5
62.0       5
71.0       5
77.0       5
82.0       4
59.0       3
58.0       3
68.0       3
47.0       3
105.0      3
82.5       3
95.0       2
73.0       2
60.9       2
104.0      1
66.5       1
15.0       1
92.0       1
67.5       1
81.0       1
61.0       1
38.0       1
Name: count, dtype: int64

--- Car_Age (22 unique) ---
Car_Age
4     267
5     262
3     218
8     192
6     186
7     178
1     156
2     132
9     128
10     92
0      81
11     79
13     33
12     27
14     13
15      6
16      2
18      1
20      1
34      1
22      1
26      1
Name: count, dtype: int64

--- Kilometers_Per_Year (1115 unique) ---
Kilometers_Per_Year
10000.0000    31
7000.0000     26
5000.0000     25
6000.0000     25
8000.0000     24
              ..
48000.0000     1
9875.0000      1
15050.0000     1
8111.1111      1
15118.5000     1
Name: count, Length: 1115, dtype: int64

--- Owner_Count (5 unique) ---
Owner_Count
1    1617
2     373
3      42
0      21
4       4
Name: count, dtype: int64

--- Unregistered (2 unique) ---
Unregistered
0    2036
1      21
Name: count, dtype: int64

--- Location_Grouped (11 unique) ---
Location_Grouped
Other        693
Mumbai       342
Delhi        307
Pune         144
Bangalore    132
Hyderabad    116
Lucknow       78
Ahmedabad     70
Chennai       63
Kolkata       60
Kanpur        52
Name: count, dtype: int64