In [13]:
import pandas as pd

In [14]:
df = pd.read_csv("../data/processed/car_new_details.csv")

In [15]:
df["Car_Age"] = 2022 - df["Year"]

In [16]:
df["Kilometers_Per_Year"] = df["Kilometer"] / df["Car_Age"].replace(0, 1)

In [19]:
owner_mapping = {
    "Unregistered Car": 0,
    "First": 1,
    "Second": 2,
    "Third": 3,
    "Fourth": 4,
    "4 or More": 4
}

df["Owner_Count"] = df["Owner"].map(owner_mapping)

df["Unregistered"] = (df["Owner"] == "Unregistered Car").astype(int)

In [20]:
df[[
    "Year",
    "Car_Age",
    "Kilometer",
    "Kilometers_Per_Year",
    "Owner",
    "Owner_Count",
    "Unregistered"
]].head(10)

,Year,Car_Age,Kilometer,Kilometers_Per_Year,Owner,Owner_Count,Unregistered
0,2017,5,87150,17430.000000,First,1,0
1,2014,8,75000,9375.000000,Second,2,0
2,2011,11,67000,6090.909091,First,1,0
3,2019,3,37500,12500.000000,First,1,0
4,2018,4,69000,17250.000000,First,1,0
5,2017,5,73315,14663.000000,First,1,0
6,2015,7,47000,6714.285714,Second,2,0
7,2017,5,75000,15000.000000,Second,2,0
8,2017,5,56000,11200.000000,First,1,0
9,2015,7,85000,12142.857143,First,1,0

In [21]:
df[[
    "Car_Age",
    "Kilometers_Per_Year",
    "Owner_Count",
    "Unregistered"
]].describe()

           Car_Age  Kilometers_Per_Year  Owner_Count  Unregistered
count  2057.000000          2057.000000  2057.000000   2057.000000
mean      5.575109         10997.023611     1.217793      0.010209
std       3.365007          7247.824147     0.493355      0.100547
min       0.000000             0.000000     0.000000      0.000000
25%       3.000000          6428.571429     1.000000      0.000000
50%       5.000000          9398.400000     1.000000      0.000000
75%       8.000000         13666.666667     1.000000      0.000000
max      34.000000        110000.000000     4.000000      1.000000

In [22]:
print("Missing values:")
print(df[[
    "Car_Age",
    "Kilometers_Per_Year",
    "Owner_Count",
    "Unregistered"
]].isnull().sum())

Missing values:
Car_Age                0
Kilometers_Per_Year    0
Owner_Count            0
Unregistered           0
dtype: int64

In [23]:
print(df["Owner_Count"].value_counts().sort_index())

Owner_Count
0      21
1    1617
2     373
3      42
4       4
Name: count, dtype: int64

In [24]:
top_locations = df["Location"].value_counts().head(10).index

df["Location_Grouped"] = df["Location"].where(
    df["Location"].isin(top_locations),
    "Other"
)

In [25]:
print(df["Location_Grouped"].value_counts())

Location_Grouped
Other        693
Mumbai       342
Delhi        307
Pune         144
Bangalore    132
Hyderabad    116
Lucknow       78
Ahmedabad     70
Chennai       63
Kolkata       60
Kanpur        52
Name: count, dtype: int64

In [26]:
df.to_csv("../data/processed/car_new_details.csv", index=False)